### ISSUE TITLE
Incorrect counters in bug status table

### ISSUE THREAD

**Issue by mmuehlfeldRH** [msuchane/cizrna#23]
The RHEL 9.2 bug status table sometimes doesn't count correctly.

For example, if I filter for my user name, the table lists 15 tickets in overall status OK and 2 in "RN not approved". However, in the counter table below, it shows "complete: 15" and "incomplete: 1"

Also, if I filter for another user, the table lists 8 tickets in overall status OK and 5 in "RN not approved". The counter table below shows "complete: 7" and "incomplete: 5"

**Comment by mmuehlfeldRH** [comment]
To not unveil any internal data, I sent @msuchane an email with the screenshots and the usernames.

**Comment by msuchane** [comment]
Thanks for the report, @mmuehlfeldRH. Off the top of my head, I can't tell why this might be happening. I'll dig through the code and try to find the root issue.

**Comment by msuchane** [comment]
Hi @mmuehlfeldRH, this bug should be fixed now.

The issue was that the first ticket that belonged to each writer didn't register in the statistics, and only the subsequent tickets did.

This wasn't as serious for writers who worked on many release notes, but for those who only worked on one, the statistics wrongly showed zero release notes as if there was no work at all.

I've released the fix in version 0.30.2. Please see the current status table in RHEL 9 and check that the numbers match.
